### ISSUE TITLE
Evaluation error: KeyError: 'categories'

### ISSUE THREAD

**Issue by zhixuanli** [apchenstu/SLN-Amodal#4]
```
100%|██████████| 1322/1322 [22:19<00:00,  1.01it/s]Loading and preparing results...
Traceback (most recent call last):
  File "/home/oliver/PycharmProjects/SLN-Amodal/amodal_eval_COCOA.py", line 670, in <module>
    evalute_amodal(dataset_val, model, limit=args.limit,args=args)
  File "/home/oliver/PycharmProjects/SLN-Amodal/amodal_eval_COCOA.py", line 440, in evalute_amodal
    coco_results = amodalGt.dataset.loadRes(results)
  File "/home/oliver/PycharmProjects/SLN-Amodal/pycocotools/coco.py", line 324, in loadRes
    res.dataset['categories'] = copy.deepcopy(self.dataset['categories'])
KeyError: 'categories'
```

Bugs report.

**Comment by zhixuanli** [comment]
I was using the COCO api download from official github repository.  But I suddenly find that your modified version is just in your repo, and it's correct.

Maybe it's better to make it be more clear in README.

Thank you for your work and the codes!
